### ISSUE TITLE
Create & answer question thought Ong Dev livestream, QnA video, etc...

### ISSUE THREAD

**Issue by thuanOwa** [OngDev/community#87]
- [ ] https://www.youtube.com/watch?v=HBrh02E9BXg
- [ ] https://www.youtube.com/watch?v=pVgJ5ZtDn5I
- [ ] https://www.youtube.com/watch?v=Clc2E5_cbF8
- [ ] https://www.youtube.com/watch?v=lvxjyhY-i8M
- [ ] https://www.youtube.com/watch?v=5CD_wEsyZf4
- [x] https://www.youtube.com/watch?v=xMzzIBevuB0
- [x] https://www.youtube.com/watch?v=B-jqB5XQmVc
- [x] https://www.youtube.com/watch?v=nFoGXqj1Ux8
- [x] https://www.youtube.com/watch?v=QbgC-F3-0L4
- [x] https://www.youtube.com/watch?v=RQH0BUSuWnk
- [x] https://www.youtube.com/watch?v=qsi0Sw0qciw
- [ ] https://www.youtube.com/watch?v=Xs-Jc7C5FFg

**Comment by thuanpham2311** [comment]
Sư huynh, sư tỷ nào muốn giúp tạo QnA mà ông dev đã trả lời cho video
Thì comment dưới đây link video mà bạn đang làm hoặc làm xong rồi nha
Các bạn có thể tham khảo những discussion có hashtab #87

**Comment by thuanOwa** [comment]
outdate
